// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/ysicing/cloudflow-api/apps/v1beta1"
	scheme "github.com/ysicing/cloudflow-api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WebsGetter has a method to return a WebInterface.
// A group's client should implement this interface.
type WebsGetter interface {
	Webs(namespace string) WebInterface
}

// WebInterface has methods to work with Web resources.
type WebInterface interface {
	Create(ctx context.Context, web *v1beta1.Web, opts v1.CreateOptions) (*v1beta1.Web, error)
	Update(ctx context.Context, web *v1beta1.Web, opts v1.UpdateOptions) (*v1beta1.Web, error)
	UpdateStatus(ctx context.Context, web *v1beta1.Web, opts v1.UpdateOptions) (*v1beta1.Web, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Web, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.WebList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Web, err error)
	WebExpansion
}

// webs implements WebInterface
type webs struct {
	client rest.Interface
	ns     string
}

// newWebs returns a Webs
func newWebs(c *AppsV1beta1Client, namespace string) *webs {
	return &webs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the web, and returns the corresponding web object, and an error if there is any.
func (c *webs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Web, err error) {
	result = &v1beta1.Web{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("webs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Webs that match those selectors.
func (c *webs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.WebList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.WebList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("webs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested webs.
func (c *webs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("webs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a web and creates it.  Returns the server's representation of the web, and an error, if there is any.
func (c *webs) Create(ctx context.Context, web *v1beta1.Web, opts v1.CreateOptions) (result *v1beta1.Web, err error) {
	result = &v1beta1.Web{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("webs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(web).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a web and updates it. Returns the server's representation of the web, and an error, if there is any.
func (c *webs) Update(ctx context.Context, web *v1beta1.Web, opts v1.UpdateOptions) (result *v1beta1.Web, err error) {
	result = &v1beta1.Web{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("webs").
		Name(web.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(web).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *webs) UpdateStatus(ctx context.Context, web *v1beta1.Web, opts v1.UpdateOptions) (result *v1beta1.Web, err error) {
	result = &v1beta1.Web{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("webs").
		Name(web.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(web).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the web and deletes it. Returns an error if one occurs.
func (c *webs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("webs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *webs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("webs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched web.
func (c *webs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Web, err error) {
	result = &v1beta1.Web{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("webs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
