run:
  deadline: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  skip-dirs:
    - apis
    - pkg/client
    - vendor
    - test
  # skip-files:
  #  - ".*\\.my\\.go$"
  #  - lib/bad.go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  gosimple:
    go: "1.19"
  unused:
    go: "1.19"
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.19"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all", "-S1*", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-SA5011", "-SA1019", "-SA2002"]
    # https://staticcheck.io/docs/options#dot_import_whitelist
    dot-import-whitelist:
      - fmt
    # https://staticcheck.io/docs/options#initialisms
    initialisms: [ "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS" ]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    http-status-code-whitelist: [ "200", "400", "404", "500" ]

  nakedret:
    # default 30
    max-func-lines: 100

  gocyclo:
    # default 30
    max-complexity: 100

  goheader:
    template-path: .go-header.txt

linters:
  fast: false
  disable-all: true
  enable:
    # TODO Enforce the below linters later
    - deadcode
    - gofmt
    - govet
    - goimports
    - ineffassign
    - misspell
    - vet
    - unconvert

issues:
  exclude:
    # staticcheck
    - 'SA1019: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead'
    # gosec: Potential hardcoded credentials
    - G101
  exclude-rules:
    # exclude ineffassing linter for generated files for conversion
    - linters:
        - dogsled
      text:  "declaration has 3 blank identifiers"
      path: _test\.go
    - linters:
        - dupl
      path: _test\.go
    - linters:
        - goheader
      source: "^//go:build"
    - linters:
        - goheader
      text: "Helm"
    - linters:
        - goheader
      text: "Kubernetes"
    - linters:
        - goheader
      text: "SPDX-License-Identifier"
    - linters:
        - goheader
      text: "Authors"
