// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	appsv1beta1 "github.com/ysicing/cloudflow-api/apps/v1beta1"
	versioned "github.com/ysicing/cloudflow-api/client/clientset/versioned"
	internalinterfaces "github.com/ysicing/cloudflow-api/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/ysicing/cloudflow-api/client/listers/apps/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GlobalDBInformer provides access to a shared informer and lister for
// GlobalDBs.
type GlobalDBInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.GlobalDBLister
}

type globalDBInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGlobalDBInformer constructs a new informer for GlobalDB type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGlobalDBInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGlobalDBInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGlobalDBInformer constructs a new informer for GlobalDB type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGlobalDBInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1beta1().GlobalDBs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1beta1().GlobalDBs(namespace).Watch(context.TODO(), options)
			},
		},
		&appsv1beta1.GlobalDB{},
		resyncPeriod,
		indexers,
	)
}

func (f *globalDBInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGlobalDBInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *globalDBInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&appsv1beta1.GlobalDB{}, f.defaultInformer)
}

func (f *globalDBInformer) Lister() v1beta1.GlobalDBLister {
	return v1beta1.NewGlobalDBLister(f.Informer().GetIndexer())
}
