// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// WebListerExpansion allows custom methods to be added to
// WebLister.
type WebListerExpansion interface{}

// WebNamespaceListerExpansion allows custom methods to be added to
// WebNamespaceLister.
type WebNamespaceListerExpansion interface{}
