// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// GlobalDBListerExpansion allows custom methods to be added to
// GlobalDBLister.
type GlobalDBListerExpansion interface{}

// GlobalDBNamespaceListerExpansion allows custom methods to be added to
// GlobalDBNamespaceLister.
type GlobalDBNamespaceListerExpansion interface{}

// WebListerExpansion allows custom methods to be added to
// WebLister.
type WebListerExpansion interface{}

// WebNamespaceListerExpansion allows custom methods to be added to
// WebNamespaceLister.
type WebNamespaceListerExpansion interface{}
